name: tests

on: push

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: dependencies
        run: bash ./ci/dependencies.sh
      - name: unit tests
        run: bash ./ci/unit_tests.sh
      - name: golden tests
        run: bash ./ci/golden_tests.sh
      - name: ruff
        run: bash ./ci/check_ruff.sh
      - name: mypy
        run: bash ./ci/check_mypy.sh
